In [19]:
print("这是云端的 Pandas 练习")

这是云端的 Pandas 练习


In [20]:
import pandas as pd
import numpy as np

In [21]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

In [22]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  str    
 2   fuel_type            10000 non-null  str    
 3   drivetrain           10000 non-null  str    
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB


In [24]:
pd.__version__

'3.0.5'

In [25]:
df.shape

(10000, 11)

In [26]:
 df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [27]:
import os
print(os.getcwd())

/workspaces/mechine-learning-zoomcamp


In [28]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [29]:
df.isnull().sum() > 0

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

In [30]:
df.isnull().any().sum()

np.int64(2)

In [31]:
df["origin"].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [32]:
asia_cars = df[df["origin"] == "Asia"]

In [33]:
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4


In [34]:
asia_cars["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [35]:
median_before = df["horsepower"].median()
median_before

np.float64(254.0)

In [36]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [37]:
mode_value = df["horsepower"].mode().iloc[0]
mode_value

np.float64(252.0)

In [38]:
horsepower_filled = df["horsepower"].fillna(mode_value)

In [39]:
horsepower_filled.isnull().sum()

np.int64(0)

In [40]:
median_after = horsepower_filled.median()
median_after

np.float64(252.0)

In [41]:
median_before, median_after

(np.float64(254.0), np.float64(252.0))

In [42]:
asia_cars = df[df["origin"] == "Asia"]

In [43]:
selected = asia_cars[["vehicle_weight", "model_year"]]

In [44]:
df["vehicle_weight"]                   # 一个Series
df[["vehicle_weight", "model_year"]]   # 一个DataFrame

,vehicle_weight,model_year
0,3870,2006
1,4210,2008
2,4240,1996
3,4490,1989
4,4510,1994
...,...,...
9995,4690,2005
9996,4370,1993
9997,4590,2014
9998,4450,2004


In [45]:
selected = selected.head(7)
selected

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [46]:
X = selected.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [47]:
X.shape

(7, 2)

In [48]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [49]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [50]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [51]:
y.shape

(7,)

In [52]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [53]:
w.sum()

np.float64(0.36919696904925486)